# Generated by Django 5.0.4 on 2024-05-25 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_is_sub_category_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
